$(document).ready(function(){
	$(".admin").click(function(){
		$(location).attr('href','adminmanage.do');
	});
	
	$(".logodiv").click(function(){
		$(location).attr('href','adminmain.do');
	});
	$("#subnav1").click(function(){
		$(location).attr('href','adminmembermanage.do');
	});
	$("#subnav2").click(function(){
		$(location).attr('href','adminproductmanage.do');
	});
	$("#subnav3").click(function(){
		$(location).attr('href','adminordermanage.do');
	});
	$("#subnav4").click(function(){
		$(location).attr('href','adminboardmanage.do');
	});
	$("#subnav5").click(function(){
		$(location).attr('href','adminpagemanage.do');
	});
	$("#subnav6").click(function(){
		$(location).attr('href','adminother.do');
	});
	$("#btbt").click(function(){
		$(location).attr('href','adminmemberdetail.do');
	});
	$("#btbtn").click(function(){
		$(location).attr('href','adminanswer.do');
	});
	$("#btbtcl").click(function(){
		$(location).attr('href','admininstitutedetail.do');
	});
	$("#sec").click(function(){
		$(location).attr('href','adminmembermanage.do');
	});
	$("#fro").click(function(){
		$(location).attr('href','adminmembermanage.do');
	});
	$("#fro1").click(function(){
		$(location).attr('href','adminmembermanage.do');
	});	
	$("#cllist").click(function(){
		$(location).attr('href','adminproductmanage.do');
	});
	$("#clplus_1").click(function(){
		$(location).attr('href','admininstituteadd.do');
	});
	$("#clplus_2").click(function(){
		$(location).attr('href','adminboardadd.do');
	});
	$(".subbtn>button").click(function(){
		$(location).attr('href','admininstitutedetail.do');
	});
	$("#clmodi").click(function(){
		$(location).attr('href','admininstitutemodify.do');
	});
	$("#btbt99").click(function(){
		$(location).attr('href','admincouresdetail.do');
	});
	$("#modibtt").click(function(){
		$(location).attr('href','admincouresmodify.do');
	});
	$("#listbt").click(function(){
		$(location).attr('href','adminproductmanage.do');
	});
	$("#savebt").click(function(){
		$(location).attr('href','admincouresdetail.do');
	});
	$("#btbt88").click(function(){
		$(location).attr('href','adminstudentdetail.do');
	});
	$("#listbtn1").click(function(){
		$(location).attr('href','adminproductmanage.do');
	});
	$("#modibtn1").click(function(){
		$(location).attr('href','adminstudentmodify.do');
	});
	$("#modibtn2").click(function(){
		$(location).attr('href','adminstudentdetail.do');
	});
	$("#btbt77").click(function(){
		$(location).attr('href','adminreviewdetail.do');
	});
	$("#starbtn").click(function(){
		$(location).attr('href','adminproductmanage.do');
	});
	$("#btbt66").click(function(){
		$(location).attr('href','admincommunitydetail.do');
	});
	$("#listbtn3").click(function(){
		$(location).attr('href','adminproductdetail.do');
	});
	$("#btbt55").click(function(){
		$(location).attr('href','adminadvicedetail.do');
	});
	$("#cmlist").click(function(){
		$(location).attr('href','adminproductmanage.do');
	});
	$("#btbt44").click(function(){
		$(location).attr('href','adminpaydetail.do');
	});
	$("#cdlist").click(function(){
		$(location).attr('href','adminordermanage.do');
	});
	$("#btbt33").click(function(){
		$(location).attr('href','adminvisitdetail.do');
	});
	$("#visitlist").click(function(){
		$(location).attr('href','adminordermanage.do');
	});
	$("#postbtn").click(function(){
		$(location).attr('href','adminboardmanage.do');
	});
	$("#postlist").click(function(){
		$(location).attr('href','adminboardmanage.do');
	});
	$("#btbtmf").click(function(){
		$(location).attr('href','adminboardmodify.do');
	});
	$("#btbt22").click(function(){
		$(location).attr('href','adminboarddetail.do');
	});
	$("#btbt11").click(function(){
		$(location).attr('href','adminreviewdetail.do');
	});
	$("#commentlist").click(function(){
		$(location).attr('href','adminboardmanage.do');
	});
	// -------------------------------------
	$("#modibt0").click(function(){
		if($(".myservice").css("display","none")) {		
			$(".myservice").css("display","block");
			$(".myservice2").css("display","none");
		}
	});
	$("#modibt").click(function(){
		if($("myservice2").css("display","none")){
			$(".myservice2").css("display","block");
			$(".myservice").css("display","none");
		}
	});	
	$("#close").click(function(){
		$(".myservice").css("display","none");			
	});
	$("#close2").click(function(){
		$(".myservice2").css("display","none");			
	});
	
	$(".navuser").click(function(){
		$(".navuser_1").toggle();
	});
	
	$("#ul2").click(function(){
		$(".ftacontent").css("display","block");
	});
	
	$(".closeimg>img").click(function(){
		$(".ftacontent").css("display","none");
	});

	$("#ftaplusbtn").click(function(){
		$(".ftacontent2").css("display","block");
		$(".cathead").css("display","block");
	});
	
	$(".closeimg2>img").click(function(){
		$(".ftacontent2").css("display","none");
		$(".cathead").css("display","none");
	});
	
	$(".catgo>button").click(function(){
		alert("미구현입니다");
	});
	
	$("#navuser_1_1").click(function(){
		$(".mainfrm").css("display","block");
		$(".mainfrm2").css("display","none");
		$(".mainfrm3").css("display","none");
		$(".mainfrm4").css("display","none");
		$(".mainfrm5").css("display","none");
		$(".mainfrm6").css("display","none");
		$(".usermainpage6").css("display","none");
		$(".usermainpage5").css("display","none");
		$(".usermainpage4").css("display","none");
		$(".usermainpage3").css("display","none");
		$(".usermainpage2").css("display","none");
		$(".usermainpage").css("display","block");
		$(".userup6").css("display","none");
		$(".userup5").css("display","none");
		$(".userup4").css("display","none");
		$(".userup3").css("display","none");
		$(".userup2").css("display","none");
		$(".userup").css("display","block");
		$(".ftaplus").css("display","none");
		$("#navuser_1_1").css("background","#FA5858");
		$("#navuser_1_2").css("background","white");
		$("#navuser_1_3").css("background","white");
		$("#navuser_1_4").css("background","white");
		$("#navuser_1_5").css("background","white");
		$("#navuser_1_6").css("background","white");
	});
	
	$("#navuser_1_2").click(function(){
		$(".mainfrm6").css("display","none");
		$(".mainfrm5").css("display","none");
		$(".mainfrm4").css("display","none");
		$(".mainfrm3").css("display","none");
		$(".mainfrm2").css("display","block");
		$(".mainfrm").css("display","none");
		$(".usermainpage").css("display","none");
		$(".usermainpage2").css("display","block");
		$(".usermainpage3").css("display","none");
		$(".usermainpage4").css("display","none");
		$(".usermainpage5").css("display","none");
		$(".usermainpage6").css("display","none");
		$(".userup").css("display","none");
		$(".userup2").css("display","block");
		$(".userup3").css("display","none");
		$(".userup4").css("display","none");
		$(".userup5").css("display","none");
		$(".userup6").css("display","none");
		$(".ftaplus").css("display","none");
		$("#navuser_1_2").css("background","#FA5858");
		$("#navuser_1_1").css("background","white");
		$("#navuser_1_3").css("background","white");
		$("#navuser_1_4").css("background","white");
		$("#navuser_1_5").css("background","white");
		$("#navuser_1_6").css("background","white");
	});
	
	$("#navuser_1_3").click(function(){
		$(".mainfrm").css("display","none");
		$(".mainfrm2").css("display","none");
		$(".mainfrm3").css("display","block");
		$(".mainfrm4").css("display","none");
		$(".mainfrm5").css("display","none");
		$(".mainfrm6").css("display","none");
		$(".usermainpage").css("display","none");
		$(".usermainpage2").css("display","none");
		$(".usermainpage3").css("display","block");
		$(".usermainpage4").css("display","none");
		$(".usermainpage5").css("display","none");
		$(".usermainpage6").css("display","none");
		$(".userup").css("display","none");
		$(".userup2").css("display","none");
		$(".userup3").css("display","block");
		$(".userup4").css("display","none");
		$(".userup5").css("display","none");
		$(".userup6").css("display","none");
		$(".ftaplus").css("display","none");
		$("#navuser_1_1").css("background","white");
		$("#navuser_1_2").css("background","white");
		$("#navuser_1_3").css("background","#FA5858");
		$("#navuser_1_4").css("background","white");
		$("#navuser_1_5").css("background","white");
		$("#navuser_1_6").css("background","white");
	});
	
	$("#navuser_1_4").click(function(){
		$(".mainfrm").css("display","none");
		$(".mainfrm2").css("display","none");
		$(".mainfrm3").css("display","none");
		$(".mainfrm4").css("display","block");
		$(".mainfrm5").css("display","none");
		$(".mainfrm6").css("display","none");
		$(".usermainpage").css("display","none");
		$(".usermainpage2").css("display","none");
		$(".usermainpage3").css("display","none");
		$(".usermainpage4").css("display","block");
		$(".usermainpage5").css("display","none");
		$(".usermainpage6").css("display","none");
		$(".userup").css("display","none");
		$(".userup2").css("display","none");
		$(".userup3").css("display","none");
		$(".userup4").css("display","block");
		$(".userup5").css("display","none");
		$(".userup6").css("display","none");
		$(".ftaplus").css("display","block");
		$("#navuser_1_1").css("background","white");
		$("#navuser_1_2").css("background","white");
		$("#navuser_1_3").css("background","white");
		$("#navuser_1_4").css("background","#FA5858");
		$("#navuser_1_5").css("background","white");
		$("#navuser_1_6").css("background","white");
	});
	
	$("#navuser_1_5").click(function(){
		$(".mainfrm").css("display","none");
		$(".mainfrm2").css("display","none");
		$(".mainfrm3").css("display","none");
		$(".mainfrm4").css("display","none");
		$(".mainfrm5").css("display","block");
		$(".mainfrm6").css("display","none");
		$(".usermainpage").css("display","none");
		$(".usermainpage2").css("display","none");
		$(".usermainpage3").css("display","none");
		$(".usermainpage4").css("display","none");
		$(".usermainpage5").css("display","block");
		$(".usermainpage6").css("display","none");
		$(".userup").css("display","none");
		$(".userup2").css("display","none");
		$(".userup3").css("display","none");
		$(".userup4").css("display","none");
		$(".userup5").css("display","block");
		$(".userup6").css("display","none");
		$(".ftaplus").css("display","none");
		$("#navuser_1_1").css("background","white");
		$("#navuser_1_2").css("background","white");
		$("#navuser_1_3").css("background","white");
		$("#navuser_1_4").css("background","white");
		$("#navuser_1_5").css("background","#FA5858");
		$("#navuser_1_6").css("background","white");
	});
	
	$("#navuser_1_6").click(function(){
		$(".mainfrm").css("display","none");
		$(".mainfrm2").css("display","none");
		$(".mainfrm3").css("display","none");
		$(".mainfrm4").css("display","none");
		$(".mainfrm5").css("display","none");
		$(".mainfrm6").css("display","block");
		$(".usermainpage").css("display","none");
		$(".usermainpage2").css("display","none");
		$(".usermainpage3").css("display","none");
		$(".usermainpage4").css("display","none");
		$(".usermainpage5").css("display","none");
		$(".usermainpage6").css("display","block");
		$(".userup").css("display","none");
		$(".userup2").css("display","none");
		$(".userup3").css("display","none");
		$(".userup4").css("display","none");
		$(".userup5").css("display","none");
		$(".userup6").css("display","block");
		$(".ftaplus").css("display","none");
		$("#navuser_1_1").css("background","white");
		$("#navuser_1_2").css("background","white");
		$("#navuser_1_3").css("background","white");
		$("#navuser_1_4").css("background","white");
		$("#navuser_1_5").css("background","white");
		$("#navuser_1_6").css("background","#FA5858");
	});
	// -------------------------------------
	
	$("#usercheck").change(function(){
		if($("#usercheck").is(":checked")){
			$("#usercheck_all1").prop("checked",true);
			$("#usercheck_all2").prop("checked",true);
			$("#usercheck_all3").prop("checked",true);
			$("#usercheck_all4").prop("checked",true);
			$("#usercheck_all5").prop("checked",true);
			$("#usercheck_all6").prop("checked",true);
			$("#usercheck_all7").prop("checked",true);
			$("#usercheck_all8").prop("checked",true);
			$("#usercheck_all9").prop("checked",true);
			$("#usercheck_all10").prop("checked",true);
			$("#usercheck_all11").prop("checked",true);
			$("#usercheck_all12").prop("checked",true);
			$("#usercheck_all13").prop("checked",true);
			$("#usercheck_all14").prop("checked",true);
			$("#usercheck_all15").prop("checked",true);
		}else {
			$("#usercheck_all1").prop("checked",false);
			$("#usercheck_all2").prop("checked",false);
			$("#usercheck_all3").prop("checked",false);
			$("#usercheck_all4").prop("checked",false);
			$("#usercheck_all5").prop("checked",false);
			$("#usercheck_all6").prop("checked",false);
			$("#usercheck_all7").prop("checked",false);
			$("#usercheck_all8").prop("checked",false);
			$("#usercheck_all9").prop("checked",false);
			$("#usercheck_all10").prop("checked",false);
			$("#usercheck_all11").prop("checked",false);
			$("#usercheck_all12").prop("checked",false);
			$("#usercheck_all13").prop("checked",false);
			$("#usercheck_all14").prop("checked",false);
			$("#usercheck_all15").prop("checked",false);
		}
	});
	
	// -------------------------------------------------
	
	
	
});