$(document).ready(function() {
	$("#an1").click(function(){
		if($("#area1").is(":visible")){
			$("#area1").css("display","none");
		}else{
			$("#area1").css("display","block");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an2").click(function(){
		if($("#area2").is(":visible")){
			$("#area2").css("display","none");
		}else{
			$("#area2").css("display","block");
			$("#area1").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an3").click(function(){
		if($("#area3").is(":visible")){
			$("#area3").css("display","none");
		}else{
			$("#area3").css("display","block");
			$("#area2").css("display","none");
			$("#area1").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an4").click(function(){
		if($("#area4").is(":visible")){
			$("#area4").css("display","none");
		}else{
			$("#area4").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an5").click(function(){
		if($("#area5").is(":visible")){
			$("#area5").css("display","none");
		}else{
			$("#area5").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an6").click(function(){
		if($("#area6").is(":visible")){
			$("#area6").css("display","none");
		}else{
			$("#area6").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an7").click(function(){
		if($("#area7").is(":visible")){
			$("#area7").css("display","none");
		}else{
			$("#area7").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an8").click(function(){
		if($("#area8").is(":visible")){
			$("#area8").css("display","none");
		}else{
			$("#area8").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});$("#an9").click(function(){
		if($("#area9").is(":visible")){
			$("#area9").css("display","none");
		}else{
			$("#area9").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an10").click(function(){
		if($("#area10").is(":visible")){
			$("#area10").css("display","none");
		}else{
			$("#area10").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an11").click(function(){
		if($("#area11").is(":visible")){
			$("#area11").css("display","none");
		}else{
			$("#area11").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an12").click(function(){
		if($("#area12").is(":visible")){
			$("#area12").css("display","none");
		}else{
			$("#area12").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an13").click(function(){
		if($("#area13").is(":visible")){
			$("#area13").css("display","none");
		}else{
			$("#area13").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an14").click(function(){
		if($("#area14").is(":visible")){
			$("#area14").css("display","none");
		}else{
			$("#area14").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an15").click(function(){
		if($("#area15").is(":visible")){
			$("#area15").css("display","none");
		}else{
			$("#area15").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area16").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an16").click(function(){
		if($("#area16").is(":visible")){
			$("#area16").css("display","none");
		}else{
			$("#area16").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area17").css("display","none");
		}
	});
	$("#an17").click(function(){
		if($("#area17").is(":visible")){
			$("#area17").css("display","none");
		}else{
			$("#area17").css("display","block");
			$("#area1").css("display","none");
			$("#area2").css("display","none");
			$("#area3").css("display","none");
			$("#area4").css("display","none");
			$("#area5").css("display","none");
			$("#area6").css("display","none");
			$("#area7").css("display","none");
			$("#area8").css("display","none");
			$("#area9").css("display","none");
			$("#area10").css("display","none");
			$("#area11").css("display","none");
			$("#area12").css("display","none");
			$("#area13").css("display","none");
			$("#area14").css("display","none");
			$("#area15").css("display","none");
			$("#area16").css("display","none");
		}
	});
	$("#option01").click(function(){
		if($(".agemain").is(":visible")){
			$(".agemain").css("display","none");
		}else{
			$(".agemain").css("display","block");
			$(".areamain").css("display","none");
			$(".subjectmain").css("display","none");
		}
	});
	$("#option02").click(function(){
		if($(".areamain").is(":visible")){
			$(".areamain").css("display","none");
		}else{
			$(".areamain").css("display","block");
			$(".agemain").css("display","none");
			$(".subjectmain").css("display","none");
		}
	});
	$("#option03").click(function(){
		if($(".subjectmain").is(":visible")){
			$(".subjectmain").css("display","none");
		}else{
			$(".subjectmain").css("display","block");
			$(".areamain").css("display","none");
			$(".agemain").css("display","none");
		}
	});
	
	// -------------------------------------------------------------------
	
	$("#movebanner").click(function(){
		$(".imgbanner").css("display","none");
		$(".imgbanner3").css("display","block");
	});
	
	$("#movebanner2").click(function(){
		$(".imgbanner").css("display","none");
		$(".imgbanner2").css("display","block");
	});
	
	$("#movebanner3").click(function(){
		$(".imgbanner").css("display","block");
		$(".imgbanner2").css("display","none");
	});
	
	$("#movebanner4").click(function(){
		$(".imgbanner").css("display","none");
		$(".imgbanner2").css("display","none");
		$(".imgbanner3").css("display","block");
	});
	
	$("#movebanner5").click(function(){
		$(".imgbanner").css("display","none");
		$(".imgbanner2").css("display","block");
		$(".imgbanner3").css("display","none");
	});
	
	$("#movebanner6").click(function(){
		$(".imgbanner").css("display","block");
		$(".imgbanner2").css("display","none");
		$(".imgbanner3").css("display","none");
	});
		
});