$(document).ready(function(){
	$(".btn1").click(function(){
		$(location).attr('href','/edupick/Institute/institute.do');
	});
	$(".btn2").click(function(){
		$(location).attr('href','paymentchange.do');
	});
	$("#creditbtn15").click(function(){
		$(location).attr('href','paymentchange.do');
	});
	$("#creditbtn16").click(function(){
		$(location).attr('href','paymentchange.do');
	});
	$("#creditbtn17").click(function(){
		$(location).attr('href','paymentchange.do');
	});
	$("#inpage1").click(function(){
		$(location).attr('href','/edupick/Institute/instituteDetail.do');
	});
	$("#inpage2").click(function(){
		$(location).attr('href','/edupick/Institute/instituteDetail.do');
	});
	$("#inpage3").click(function(){
		$(location).attr('href','/edupick/Institute/instituteDetail.do');
	});
});