$(document).ready(function(){
	$("#tab2").click(function(){
		$("#content1").css("display","none");
	});
	$("#tab1").click(function(){
		$("#content1").css("display","block");
	});
	$("#tab3").click(function(){
		$("#content1").css("display","none");
	});
});